export const PRODUCTS = [
  {
    id: 1,
    name: 'Ківі-Йогурт',
    flavor: 'kiwi',
    slug: 'kiwi-yogurt',
    price: 49,
    oldPrice: 65,
    weight: '100g',
    emoji: '🥝',
    color: '#84cc16',
    bgColor: '#f7fee7',
    tagline: 'Зелена сила',
    description: 'Натуральний йогурт з кімчі та шматочками ківі. Заряджає енергією та підтримує імунітет.',
    ingredients: 'Йогурт 2.5%, ківі 30%, сироп агави, горіхи кеш\'ю',
    calories: 142,
    protein: 6.2,
    fat: 3.1,
    carbs: 22.4,
    badge: 'ХІТ',
    badgeColor: '#84cc16',
    rating: 4.8,
    reviews: 234,
    category: 'yogurt',
  },
  {
    id: 2,
    name: 'Манго-Чіа',
    flavor: 'mango',
    slug: 'mango-chia',
    price: 55,
    weight: '100g',
    emoji: '🥭',
    color: '#f5a623',
    bgColor: '#fffbeb',
    tagline: 'Тропічний вибух',
    description: 'Пудинг з насінням чіа та справжнім манго. Суперфуд для суперлюдей.',
    ingredients: 'Насіння чіа 20%, манго 40%, кокосове молоко, мед',
    calories: 168,
    protein: 4.8,
    fat: 5.2,
    carbs: 28.1,
    badge: 'NEW',
    badgeColor: '#f5a623',
    rating: 4.9,
    reviews: 187,
    category: 'chia',
  },
  {
    id: 3,
    name: 'Малина-Шоко',
    flavor: 'berry',
    slug: 'raspberry-choco',
    price: 59,
    weight: '100g',
    emoji: '🍫',
    color: '#e84393',
    bgColor: '#fdf2f8',
    tagline: 'Солодкий баланс',
    description: 'Темний шоколад з малиновою начинкою. Антиоксиданти та ендорфіни в одному шматочку.',
    ingredients: 'Темний шоколад 70%, малина 25%, кокосове масло',
    calories: 195,
    protein: 3.4,
    fat: 11.2,
    carbs: 24.6,
    badge: 'ТОП',
    badgeColor: '#e84393',
    rating: 4.7,
    reviews: 312,
    category: 'chocolate',
  },
  {
    id: 4,
    name: 'М\'ята-Протеїн',
    flavor: 'mint',
    slug: 'mint-protein',
    price: 69,
    weight: '120g',
    emoji: '🌿',
    color: '#4ecb8c',
    bgColor: '#f0fdf4',
    tagline: 'Максимум протеїну',
    description: 'Протеїновий батончик зі смаком свіжої м\'яти. 25г протеїну — ідеально після тренування.',
    ingredients: 'Протеїн сироватки 30%, м\'ята 5%, темний шоколад, горіхи',
    calories: 218,
    protein: 25.0,
    fat: 7.8,
    carbs: 16.2,
    badge: 'PRO',
    badgeColor: '#4ecb8c',
    rating: 4.6,
    reviews: 156,
    category: 'protein',
  },
  {
    id: 5,
    name: 'Банан-Горіх',
    flavor: 'mango',
    slug: 'banana-nut',
    price: 52,
    weight: '100g',
    emoji: '🍌',
    color: '#fbbf24',
    bgColor: '#fefce8',
    tagline: 'Класика спорту',
    description: 'Банановий смузі-бар з мигдалем та пеканом. Повільні вуглеводи для тривалої енергії.',
    ingredients: 'Банан 45%, мигдаль 20%, пекан 15%, вівсяні пластівці',
    calories: 178,
    protein: 5.6,
    fat: 8.4,
    carbs: 26.8,
    badge: null,
    rating: 4.5,
    reviews: 98,
    category: 'bar',
  },
  {
    id: 6,
    name: 'Чорниця-Лаванда',
    flavor: 'berry',
    slug: 'blueberry-lavender',
    price: 62,
    weight: '100g',
    emoji: '🫐',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    tagline: 'Антистрес снек',
    description: 'Збалансований десерт з чорницею та лавандою. Заспокоює та заряджає одночасно.',
    ingredients: 'Чорниця 35%, лаванда 2%, йогурт, мед гречаний',
    calories: 151,
    protein: 4.9,
    fat: 2.8,
    carbs: 29.4,
    badge: 'CALM',
    badgeColor: '#8b5cf6',
    rating: 4.8,
    reviews: 203,
    category: 'yogurt',
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'Всі продукти', emoji: '✨' },
  { id: 'yogurt', label: 'Йогурти', emoji: '🥛' },
  { id: 'chocolate', label: 'Шоколад', emoji: '🍫' },
  { id: 'protein', label: 'Протеїн', emoji: '💪' },
  { id: 'chia', label: 'Чіа пудинг', emoji: '🌱' },
  { id: 'bar', label: 'Батончики', emoji: '🍫' },
]
